# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

pool:
  vmImage: ubuntu-latest
strategy:
  matrix:
    Python37:
      python.version: '3.7'

steps:
- task: DownloadPackage@1
  inputs:
    packageType: 'upack'
    feed: '7e2508b7-16ef-40ce-85b8-b565673fcfdb/798e57f2-935d-4895-8079-1db15fda034c'
    view: 'c215f40e-9362-4de4-8df4-4b56f2936346'
    definition: 'c4e76191-1448-4178-a432-060d27437f2c'
    version: '0.0.1'
    downloadPath: '$(System.ArtifactsDirectory)'
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python3 -m pip install --upgrade pip
    pip3 install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    python3 main.py
  displayName: 'run script'

- task: PublishBuildArtifacts@1
  displayName: 'publish artifacts'
  inputs:
    PathtoPublish: './switch.db'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: CopyFiles@2
  inputs:
    contents: './switch.db'
    TargetFolder: $(Build.ArtifactStagingDirectory)

- task: UniversalPackages@0
  inputs:
    command: 'publish'
    publishDirectory: '$(Build.ArtifactStagingDirectory)'
    feedsToUsePublish: 'internal'
    vstsFeedPublish: '7e2508b7-16ef-40ce-85b8-b565673fcfdb/798e57f2-935d-4895-8079-1db15fda034c'
    vstsFeedPackagePublish: 'switchdb'
    versionOption: 'patch'